spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hogwarts
    initialization-mode: ALWAYS
    username: student
    password: chocolatefrog
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update