spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hogwarts
    username: student
    password: chocolatefrog
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
server:
  port: 8181